import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Auth",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/update-authentication-configuration",
          label: "Update authentication configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/retrieve-authentication-configuration",
          label: "Retrieve authentication configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/twitch-o-auth-callback",
          label: "Twitch OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/slack-o-auth-callback",
          label: "Slack OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/google-o-auth-callback",
          label: "Google OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/git-hub-o-auth-callback",
          label: "GitHub OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/discord-o-auth-callback",
          label: "Discord OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/custom-o-auth-callback",
          label: "Custom OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/user-exists",
          label: "User exists",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/register-user",
          label: "Register user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/setup-lunalytics",
          label: "Setup Lunalytics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/login-with-credentials",
          label: "Login with credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/logout-current-user",
          label: "Logout current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/redirect-to-o-auth-provider",
          label: "Redirect to OAuth provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/check-if-setup-exists",
          label: "Check if setup exists",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "User",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/get-user",
          label: "Get User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/user-exists",
          label: "User Exists",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-workspaces",
          label: "Get Workspaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-connections",
          label: "Get Connections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-avatar",
          label: "Update Avatar",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/remove-user",
          label: "Remove User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-account",
          label: "Delete Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/decline-access",
          label: "Decline Access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/approve-access",
          label: "Approve Access",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-username",
          label: "Update Username",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-password",
          label: "Update Password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-settings",
          label: "Update Settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/create-connection",
          label: "Create Connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-connection",
          label: "Delete Connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-permissions",
          label: "Update Permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/transfer-ownership",
          label: "Transfer Ownership",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tokens",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/create-token",
          label: "Create token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-token",
          label: "Delete token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-token",
          label: "Update token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Monitor",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/pause-monitor",
          label: "Pause Monitor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-monitor",
          label: "Delete Monitor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/edit-monitor",
          label: "Edit Monitor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/add-monitor",
          label: "Add Monitor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/monitor-status",
          label: "Monitor Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-monitor-by-id",
          label: "Get Monitor By ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Invites",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/get-all-invites",
          label: "Get All Invites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-invite",
          label: "Create Invite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/pause-invite",
          label: "Pause Invite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-invite",
          label: "Delete Invite",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Incident",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/create-incident",
          label: "Create Incident",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-incident",
          label: "Delete Incident",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-incident",
          label: "Update Incident",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/create-incident-message",
          label: "Create Incident Message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-incident-message",
          label: "Delete Incident Message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-incident-message",
          label: "Update Incident Message",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Provider",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/delete-o-auth-provider",
          label: "Delete OAuth provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/configure-o-auth-providers",
          label: "Configure OAuth providers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-providers",
          label: "Get providers",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Workspace",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/create-workspace",
          label: "Create Workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-current-member",
          label: "Get Current Member",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workspace-members",
          label: "Get Workspace Members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workspace-monitors",
          label: "Get Workspace Monitors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workspace-notifications",
          label: "Get Workspace Notifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workspace-incidents",
          label: "Get Workspace Incidents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workspace-status-pages",
          label: "Get Workspace Status Pages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workspace-api-tokens",
          label: "Get Workspace API Tokens",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Status-pages",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/get-status-page-by-id",
          label: "Get Status Page By ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-status-page",
          label: "Create Status Page",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-status-page",
          label: "Update Status Page",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-status-page",
          label: "Delete Status Page",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Notification",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/get-notification-by-id",
          label: "Get Notification By ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-notification",
          label: "Create Notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/edit-notification",
          label: "Edit Notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-notification",
          label: "Delete Notification",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/toggle-notification",
          label: "Toggle Notification",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/test-notification",
          label: "Test Notification",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
